name: Deploy Go Application

on: 
  push:
    branches: 
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "DATABASE_NAME=${{secrets.DATABASE_NAME}}" >> .env
          echo "MONGODB_URI=${{secrets.MONGODB_URI}}" >> .env

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t jefferyokesamuel/christville .

      - name: Push image to docker hub
        run: docker push jefferyokesamuel/christville:latest

deploy:
  needs: build
  runs-on: self-hosted
  steps:
    - name: Pull docker image
      run: docker pull jefferyokesamuel/christville:latest
    - name: Delete old container
      run: docker rm -f christ-container
    - name: Run docker container
      run: docker run -d -p 8080:8080 --name christ-container jefferyokesamuel/christville
